; PlatformIO Project Configuration File
;  this is for ease of uploading different code to 
;  different boards in the circuit

[env:common]
platform = espressif32
;board = esp32doit-devkit-v1
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
lib_deps = knolleary/PubSubClient@^2.8
    kosme/arduinoFFT@^2.0.2
	Heltec ESP32 Dev-Boards @ 2.1.5
	adafruit/Adafruit BusIO @ 1.17.0
	adafruit/Adafruit GFX Library @ 1.11.11
build_src_filter =
	+<*.h>
	-<.git/>
	-<.svn/>
	+<shared/>
	+<${PIOENV}/>
	+<main-${PIOENV}.cpp>
build_flags =
	-D OVER_THE_AIR_ACTIVATION
	-D LORAWAN_REGION_EU868
	-D LORAWAN_CLASS_A
	-D BOARD_HELTEC_WIFI_LORA_32_V3
	-D SLOW_CLK_TPYE=0
	-D LoRaWAN_DEBUG_LEVEL=0
	-D REGION_EU868
	-D GPIO_PIN_COUNT=SOC_GPIO_PIN_COUNT
	-D ACTIVE_REGION=LORAMAC_REGION_EU868
	-D USE_SX1262_RADIO
    -D SX126x_BOARD
	-D HELTEC_BOARD=30
	-D HELTEC_WIFI_LORA_32_V3
	-D WIFI_LORA_32_V3
	-D MCU_ESP32_S3
	-D RADIO_CHIP_SX1262

[env:sampler]
extends = env:common

[env:monitor]
extends = env:common
lib_deps = adafruit/Adafruit INA219

