; PlatformIO Project Configuration File
;  this is for ease of uploading different code to 
;  different boards in the circuit

[env:common]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps = knolleary/PubSubClient@^2.8
    kosme/arduinoFFT@^2.0.2
build_src_filter =
	+<*.h>
	-<.git/>
	-<.svn/>
	+<shared/>
	+<${PIOENV}/>
	+<main-${PIOENV}.cpp>

[env:sampler]
extends = env:common

[env:monitor]
extends = env:common
lib_deps = adafruit/Adafruit INA219

